name: My first pipeline

on:
 workflow_dispatch:

jobs:
  build:
   runs-on: [self-hosted, wsl-ubuntu]

   steps:
    - name: My first pipeling
      run: echo "My first pipeline"

  deploy:
    needs: build
    runs-on: [self-hosted, wsl-ubuntu]

    steps: 
     - name: my second job
       run: echo "My second job"
