name: My first pipeline

on:
 push:
  branches: ["main"]

jobs:
  firstpipeline:
   runs-on: [self-hosted, wsl-ubuntu]

   steps:
    - name: My first pipeling
      run: echo "My first pipeline"

  deploy:
    runs-on: [self-hosted, wsl-ubuntu]

    steps: 
     - name: my second job
       run: echo "My second job"
