name: My node basic pipeline

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  node:
    runs-on: [self-hosted, wsl-ubuntu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install packages
        run: npm install

      - name: Debug variables
        run: |
          echo "APP=${{ vars.APP }}" >> .env.development
          echo "PORT=${{ vars.PORT }}" >> .env.development

          echo "----- ENV FILE -----"
          cat .env.development

      - name: Run application
        run: |
          node --env-file=.env.development server.js &
          sleep 5
          pkill -f "node --env-file=.env.development server.js"
