name: Sample pipeline



# on: 
#    push:
#        branches: ["main"]

on: 
 workflow_dispatch:
jobs:
    build:
        runs-on: [self-hosted, wsl-ubuntu]       

        steps:
            - name: Sample step
              run: echo "Sample pipeline"

    deploy:
        needs: build
        runs-on: [self-hosted, wsl-ubuntu]

        steps:
             - name: Deploy step
               run: echo "Deploye pipeline"
               
         
