name: sonarqube pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  sonarqube:
    runs-on: [self-hosted, wsl-ubuntu]

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: run sonarqube analysis
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          args: >
            -Dsonar.projectKey=NodeApplication
            -Dsonar.sources=.
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
